### ISSUE TITLE
Extra comma in generated CRuleFamilies

### ISSUE THREAD

**Issue by tfrost** [pavkam/tzdb#14]
An extra comma can appear after the last item.  I have fixed it in TZSchema.pas by adding a new local integer variable `nFamilies`.  Then before the loop to generate this array add:
   `nFamilies := FRuleFamilies.Count - LGhosts;`
and instead of the test to write the comma:
     ` Dec(nFamilies);`
      `if nFamilies > 0 then Write(LFile, ',');`

**Comment by pavkam** [comment]
Thanks, I have applied a fix. Will test later.
