### ISSUE TITLE
Windows alias translation table (from CLDR project) linked is not latest

### ISSUE THREAD

**Issue by rsarvi** [pavkam/tzdb#20]
Hi.

Windows alias translation table (from CLDR project) linked is not latest. It is still 2018i?

Could you please link the latest one? 

Thanks

**Comment by pavkam** [comment]
Hi @rsarvi,

The CLDR translation table is not part of IANA TZDB so the version is not 2018i. But, in latest TZDB (1.9.2018b) the latest CLDR data was applied.

In previous version, I think the CLDR data was not refreshed for a couple of years.

I created a shell script that pulls all the latest data and compiles it into a new release and that would have taken care of it.

Alex.

**Comment by pavkam** [comment]
Closing as there's no further details on this.
