### ISSUE TITLE
Incompatible types 'TTimeZone' and 'TBundledTimeZone'

### ISSUE THREAD

**Issue by redpeds** [pavkam/tzdb#29]
Hello,

When i tried to execute the example:

var
  LAmsterdam: TTimeZone;
begin
  LAmsterdam := TBundledTimeZone.GetTimeZone('Europe/Amsterdam');
  ...
  ...
end;

I got the error saying that LAmsterdam is a TTimeZone not compatible with TBundledTimeZone.

Do you know how to fix this?

**Comment by pavkam** [comment]
The "newest" (2019) version of TZDB splits the `TBundledTimeZone` from `TTimeZone` due to design issues. Use `TBundledTimeZone` as the only type from 2019.
