### ISSUE TITLE
Obsolete data

### ISSUE THREAD

**Issue by Guba666** [pavkam/tzdb#30]
There is a new release of TZ data updated at 2020.
I'm new to GIT so I write this problem here.
Please move this issue somewhere else more appropriate in the repository if it is necessary.
Please publish some kind of HOW-TO document on updating the TZ database ny oneself.
Thanks.

**Comment by pavkam** [comment]
Thank you for the report -- This is the correct way of reporting issues.

I have updated the library to the latest version of TZDB and updated the `README` file to include the steps for updating it manually.
