### ISSUE TITLE
ToISO8601Format: missing "T" date-time separator and documentation error

### ISSUE THREAD

**Issue by rr-rosendahl** [pavkam/tzdb#38]
Hi,

the ToISO8601Format function returns a string where time and date are separated by a space. According to the iso 8601 spec, the date and time should be separated by the letter "T". Could you change that in the CZFormat and CFullFormat in the implementation of the function?

Also, the documentation (in dist/TZDB.pas) says that the ADateTime should be a utc timestamp. However, the function only appends the timezone bias, but does not convert the date/time from utc to local. That means that if you pass a utc TDateTime into the function, it will output the utc date and time but with the local timezone bias, resulting in the wrong time. Could you change the documentation to say that the function accepts a local TDateTime (and not a utc one)? The function then works as expected. I think it actually makes more sense to pass a local TDateTime into the function, as it only formats it to an iso 8601 string. It doesn't have to convert the TDateTime from utc to local, since there's already another function to do that.

**Comment by pavkam** [comment]
Thanks @rr-rosendahl -- I have applied a fix to the code for `T` and a fix to the documentation to specify the time is local, not UTC.
