### ISSUE TITLE
A problem with Argentina /Buenos aires time regime

### ISSUE THREAD

**Issue by Guba666** [pavkam/tzdb#39]
I'm trying to create a birth chart for Diego Armando Maradona 30 October 1960 at 07:05
The data on IANA says that at the day/time of birth it was active the daylight saving time (+ 1 hour), so the correct time is  ADT h3w (GMT-3)
The program of visualization says that in 1960 there was not any daylight saving time active.
These are the data of the time zone active onto IANA:
Buenos Aires DLST From 01/10/1946 00:00 to 01/10/1963 00:00 
Please double check the data because it seems to be a problem of reliability of your precious project.

**Comment by Guba666** [comment]
[southamerica.zip](https://github.com/pavkam/tzdb/files/6217700/southamerica.zip)
I add here the original file where I've got the data.
Please tell me something.
Thanks in advance.

**Comment by pavkam** [comment]
@Guba666, the rules are as follows:
```
Rule	Arg	1946	only	-	Oct	 1	0:00	1:00	-
Rule	Arg	1963	only	-	Oct	 1	0:00	0	-
``
The dates you specified are `only`. Which means that 1946 applied to 1946 only,
