### ISSUE TITLE
Cannot compile TZDB.pas in Android and iOS platform due to usage of unit contnrs

### ISSUE THREAD

**Issue by ccy** [pavkam/tzdb#5]
tzdb cannot compile in Android and iOS platform due to the usage of unit contnrs.  I think TBucketList may be replaced by TDictionary.

**Comment by pavkam** [comment]
Thanks for your bug report. @mbtaylor1982 you mind giving it a look? I've got not Delphi license.

**Comment by pavkam** [comment]
@ccy, As far as I remember, the **TBitBucket** was used due to it being shared across _Delphi and FPC_. **TDictionary** was not compatible at the time. I am not sure now what is going on,

**Comment by ccy** [comment]
Your code base was designed to work for both Delphi and FPC.  FPC might not have TDictionary.

**Comment by mbtaylor1982** [comment]
I’m busy moving house and with work commitments right now but as soon as I’m free I’ll take a look.

**Comment by ccy** [comment]
I have done the fix: https://github.com/pavkam/tzdb/pull/6

**Comment by pavkam** [comment]
Thanks @mbtaylor1982, no worries about it. @ccy, I'll give it a look.

**Comment by pavkam** [comment]
Merged the PR
